version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.9-rc-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: start selenium GRID
          command: |
            chmod +x tools/selenium-server-standalone-3.141.59.jar
            java -jar tools/selenium-server-standalone-3.141.59.jar -role node -hub http://localhost:4444 &
            java -jar tools/selenium-server-standalone-3.141.59.jar -role hub -hubConfig tools/hubConfig.json -debug &
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: run smoke_api tests
          command: |
            . venv/bin/activate
             python3 -m pytest -m smoke_api -v

      - run:
          name: run ui_smoke tests
          command: |
            . venv/bin/activate
             python3 -m pytest -m smoke -v

      - run:
          name: run ui_regression tests
          command: |
            . venv/bin/activate
             python3 -m pytest -m regression -v