version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.9-rc-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: run smoke_api tests
          command: |
            . venv/bin/activate
             python3 -m pytest -m smoke_api -v

      - run:
          name: run smoke_api tests
          command: |
            . venv/bin/activate
             python3 -m pytest -m smoke -v

      - run:
          name: run smoke_api tests
          command: |
            . venv/bin/activate
             python3 -m pytest -m regression -v